const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const root=path.resolve(process.argv[2]),port=Number(process.argv[3]||4188);
const user={id:'benchmark-user',username:'medicion',plan:'PRO',role:'USER',subscriptionStatus:'ACTIVE',isProfilePublic:true,showStats:true,isCreator:true,avatarUrl:null};
const token='eyJhbGciOiJIUzI1NiJ9.'+Buffer.from(JSON.stringify({iss:'finix-api',sub:user.id,exp:2000000000})).toString('base64url')+'.benchmark';
const author={id:'benchmark-author',username:'Finix',avatarUrl:null,plan:'PRO',isVerified:true};
const posts=Array.from({length:45},(_,i)=>({id:'post-'+i,content:'Seguimiento del mercado: una publicación de prueba para medir carga y navegación.',createdAt:'2026-10-03T15:00:00Z',type:'post',author,media:[],likes:[],_count:{likes:2,replies:0,comments:0,reposts:0,quotes:0,saves:0}}));
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/')){await new Promise(r=>setTimeout(r,u.pathname==='/api/mercadopago/config'?250:40));let data={};const p=u.pathname.slice(4);if(p==='/auth/me')data=user;else if(p==='/mercadopago/config')data={freeAccessEnabled:true,purchasesPaused:true};else if(p==='/posts/feed'){const start=u.searchParams.has('cursor')?Number(u.searchParams.get('cursor').split('-')[1])+1:0;const items=posts.slice(start,start+20);data={posts:items,hasMore:start+20<posts.length,nextCursor:start+20<posts.length?items.at(-1).id:null}}else if(p.includes('unread-count'))data={count:0};else if(p.includes('rankings/top-'))data={items:[],isStale:false};else if(p==='/stories/feed')data=[];else if(p==='/news/slots/headlines'||p==='/news/slots/categories'||p==='/portfolios/watchlists'||p==='/communities'||p.includes('leaderboard'))data=[];else if(p==='/portfolios')data=[];res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify(data));}
let file=path.join(root,decodeURIComponent(u.pathname));if(!file.startsWith(path.resolve(root)+path.sep)&&file!==path.resolve(root))return res.writeHead(403).end();if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(root,'index.html');let bytes=fs.readFileSync(file);if(file.endsWith('index.html'))bytes=Buffer.from(bytes.toString().replace('<head>',`<head><script>localStorage.setItem('user',${JSON.stringify(JSON.stringify(user))});localStorage.setItem('token',${JSON.stringify(token)});localStorage.setItem('refreshToken','benchmark');localStorage.setItem('finix_cookie_consent','accepted');</script>`));const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2','.json':'application/json'}[path.extname(file)]||'application/octet-stream';const headers={'content-type':type,'cache-control':'no-store'};if(/gzip/.test(req.headers['accept-encoding']||'')){bytes=zlib.gzipSync(bytes);headers['content-encoding']='gzip'}res.writeHead(200,headers);res.end(bytes);
}).listen(port,'127.0.0.1',()=>console.log(`Measurement server port ${port}`));
