import { useCallback, useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { LockKeyhole, Plus, Download, Wallet } from 'lucide-react';
import { useAuthStore } from '@/stores/authStore';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Empty, Field, fieldClass, financeAccess, financeRequest, kinds, meta, money, Surface, today } from '@/features/finance/workspaceShared';
import { WorkspaceEditor } from '@/features/finance/WorkspaceEditor';
import { WorkspaceImport } from '@/features/finance/WorkspaceImport';
import { WorkspaceSettings } from '@/features/finance/WorkspaceSettings';

const tabs = [['', 'Resumen'], ['movimientos', 'Movimientos'], ['cuentas', 'Cuentas'], ['tarjetas', 'Tarjetas'], ['calendario', 'Próximos meses'], ['presupuestos', 'Presupuestos'], ['objetivos', 'Metas'], ['analytics', 'Informes'], ['importar', 'Importar'], ['configuracion', 'Ajustes']];
const resources: Record<string, string> = { cuentas: 'accounts', tarjetas: 'cards', presupuestos: 'budgets', objetivos: 'goals' };

export default function FinanceWorkspace() {
    const user = useAuthStore(s => s.user);
    if (!financeAccess(user)) return <div className="mx-auto max-w-2xl p-6"><Surface title="Finanzas Personales"><LockKeyhole className="mb-4 h-8 w-8 text-primary" /><p className="mb-5 text-muted-foreground">Tu espacio privado para organizar gastos, cuotas y metas está incluido en Pro y Creador. No se cargaron datos financieros.</p><Link className="text-primary underline" to="/settings">Ver mi plan</Link></Surface></div>;
    return <PrivateWorkspace key={user?.id} />;
}

function PrivateWorkspace() {
    const location = useLocation();
    const navigate = useNavigate();
    const tab = location.pathname.split('/')[2] || '';
    const [month, setMonth] = useState(today().slice(0, 7));
    const [currency, setCurrency] = useState('ARS');
    const [snapshot, setSnapshot] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [message, setMessage] = useState('');
    const [editor, setEditor] = useState<any>(null);
    const [confirmation, setConfirmation] = useState<any>(null);
    const [confirmationText, setConfirmationText] = useState('');
    const [busy, setBusy] = useState(false);
    const [search, setSearch] = useState('');
    const [status, setStatus] = useState('all');
    const [type, setType] = useState('all');
    const [category, setCategory] = useState('all');
    useEffect(() => {
        if (new URLSearchParams(location.search).get('new') === 'expense') {
            setEditor({ resource: 'transactions' });
            navigate(location.pathname, { replace: true });
        }
    }, [location.search, location.pathname, navigate]);
    const reload = useCallback(async () => {
        const data = await financeRequest(`snapshot?month=${encodeURIComponent(month)}&currency=${currency}`);
        setSnapshot(data);
    }, [month, currency]);
    useEffect(() => {
        let current = true;
        setLoading(true); setError('');
        financeRequest(`snapshot?month=${encodeURIComponent(month)}&currency=${currency}`).then(data => { if (current) setSnapshot(data); }).catch(e => { if (current) setError(e.message); }).finally(() => { if (current) setLoading(false); });
        return () => { current = false; };
    }, [month, currency]);
    const edit = (resource: string, row?: any) => setEditor({ resource, row });
    async function download() {
        setBusy(true); setMessage('');
        try {
            const data = await financeRequest('export');
            for (const [key, filename] of [['transactions', 'movimientos'], ['categories', 'categorias']]) {
                const url = URL.createObjectURL(new Blob([data[key]], { type: 'text/csv;charset=utf-8' }));
                const a = document.createElement('a'); a.href = url; a.download = `finix-${filename}-${today()}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
            }
            setMessage('Exportación generada. Los archivos contienen información privada: guardalos en un lugar seguro.');
        } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
    }
    async function execute() {
        setBusy(true); setMessage('');
        try {
            if (confirmation.erase) await financeRequest('erase', { confirmation: confirmationText });
            else if (confirmation.contribute) await financeRequest(`goals/${confirmation.row.id}/contributions`, { amount: Number(confirmationText) });
            else await financeRequest(`${confirmation.resource}/${confirmation.row.id}`, undefined, 'DELETE');
            await reload(); setConfirmation(null); setConfirmationText(''); setMessage('Cambios guardados.');
        } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
    }
    const actions = (resource: string, row: any) => <div className="flex shrink-0 gap-1"><Button size="sm" variant="ghost" onClick={() => edit(resource, row)}>Editar</Button><Button size="sm" variant="ghost" onClick={() => { setConfirmation({ resource, row }); setConfirmationText(''); }}>Eliminar</Button></div>;
    const s = snapshot?.summary;
    const transactions = snapshot?.transactions.filter((t: any) => t.date.startsWith(month) && t.currency === currency && (status === 'all' || t.status === status) && (type === 'all' || t.type === type) && (category === 'all' || t.category === category || meta(t).splits?.some((v: any) => v.category === category)) && `${t.description} ${t.merchant || ''} ${t.notes || ''}`.toLowerCase().includes(search.toLowerCase())).sort((a: any, b: any) => b.date.localeCompare(a.date)) || [];
    return <main className="mx-auto w-full max-w-7xl space-y-5 p-4 pb-28 sm:p-6 sm:pb-28">
        <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 flex items-center gap-1.5 text-xs font-medium text-primary"><LockKeyhole size={13} />Solo vos · Pro / Creador</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Finanzas Personales</h1><p className="mt-2 text-sm text-muted-foreground">Tus gastos, tus próximos pagos y un poco más de claridad.</p></div><div className="flex gap-2"><Button variant="outline" disabled={busy || !snapshot || loading} onClick={download}><Download size={15} className="mr-2" />Exportar</Button><Button disabled={!snapshot || loading || !!error} onClick={() => edit('transactions')}><Plus size={16} className="mr-2" />Movimiento</Button></div></header>
        <nav aria-label="Finanzas personales" className="flex gap-1 overflow-x-auto rounded-2xl border border-border bg-card p-1.5">{tabs.map(([path, label]) => <Link key={path} aria-current={tab === path ? 'page' : undefined} className={`whitespace-nowrap rounded-xl px-3 py-2 text-sm font-medium transition-colors ${tab === path ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-secondary'}`} to={`/finanzas${path ? '/' + path : ''}`}>{label}</Link>)}</nav>
        <div className="flex flex-wrap items-end gap-3"><Field label="Período"><input type="month" min="2000-01" max="2100-12" className={fieldClass} value={month} onChange={e => e.target.value && setMonth(e.target.value)} /></Field><Field label="Moneda original"><select className={fieldClass} value={currency} onChange={e => setCurrency(e.target.value)}>{['ARS', 'USD', 'EUR'].map(c => <option key={c}>{c}</option>)}</select></Field><p className="max-w-lg pb-2 text-xs text-muted-foreground">Carga manual e importaciones. No es una conexión bancaria ni un saldo verificado. No se suman monedas distintas.</p></div>
        {message && <p role="status" className="rounded-xl border border-border bg-secondary p-3 text-sm">{message}</p>}
        {loading ? <p role="status" className="py-12 text-center text-muted-foreground">Cargando tu espacio privado…</p> : error ? <Surface><p role="alert" className="mb-4 text-destructive">{error}</p><Button variant="outline" onClick={async () => { try { await reload(); setError(''); } catch (e) { setError((e as Error).message); } }}>Reintentar</Button></Surface> : snapshot && <>
            {snapshot.transactions.length === 0 && !['importar', 'configuracion'].includes(tab) && <Surface><div className="flex items-start gap-4"><Wallet className="mt-1 h-8 w-8 shrink-0 text-primary" /><div><h2 className="font-semibold">Empezá con lo que sabés</h2><p className="mt-1 text-sm text-muted-foreground">Agregá una cuenta, registrá un ingreso y cargá tu primer gasto. No completamos cifras por vos.</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => edit('accounts')}>Crear cuenta</Button><Button size="sm" variant="outline" onClick={() => edit('transactions', { type: 'income' })}>Cargar ingreso</Button><Link className="p-2 text-sm text-primary" to="/finanzas/importar">Importar CSV</Link></div></div></div></Surface>}
            {(tab === '' || tab === 'analytics') && <>
                <Surface><div className="grid gap-5 sm:grid-cols-3">{[['Ingresos registrados', s.income], ['Gastos netos registrados', s.expenses], ['Diferencia del mes', s.difference]].map(([label, value]) => <div key={label as string}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{money(value, currency)}</p></div>)}</div><p className="mt-4 text-xs text-muted-foreground">Sólo movimientos confirmados · {s.pendingCount} pendientes de revisión en este mes. Las devoluciones reducen gastos; los pagos de tarjeta y transferencias no son nuevos gastos.</p></Surface>
                {!s.estimate.hidden && <Surface title="Disponible estimado según tus datos"><p className="text-3xl font-semibold tracking-tight text-primary">{money(s.estimate.value, currency)}</p><p className="mt-2 text-sm text-muted-foreground">{s.estimate.incomplete ? 'Información incompleta: faltan ingresos, revisión de movimientos o confirmación de tus compromisos.' : 'Estimación basada en los registros que confirmaste. No es tu saldo bancario.'}</p><details className="mt-4 text-sm"><summary className="cursor-pointer font-medium">Ver fórmula y datos usados</summary><p className="my-3 text-muted-foreground">{s.estimate.formula}</p><div className="grid gap-2 sm:grid-cols-2">{[['Ingresos', s.estimate.income], ['Salidas pagadas', s.estimate.paid], ['Compromisos del mes y atrasados', s.estimate.commitments], ['Presupuesto variable restante', s.estimate.variableBudget], ['Reserva elegida', s.estimate.reserve]].map(([label, v]) => <p key={label as string}>{label}: {money(v, currency)}</p>)}</div></details><p className="mt-4 text-xs text-muted-foreground">No es una recomendación de inversión. No incluye saldos iniciales, ni mueve dinero. <Link className="text-primary underline" to="/finanzas/configuracion">Ajustar reserva, supuestos u ocultar</Link></p></Surface>}
                <div className="grid gap-5 lg:grid-cols-2"><Surface title="En qué gastaste">{s.categories.filter((c: any) => c.amount !== 0).length ? <div className="space-y-3">{s.categories.filter((c: any) => c.amount !== 0).sort((a: any, b: any) => b.amount - a.amount).map((c: any) => <div key={c.category} className="flex justify-between gap-3 text-sm"><span>{c.category}</span><span className="tabular-nums">{money(c.amount, currency)}</span></div>)}<p className="border-t border-border pt-3 text-xs text-muted-foreground">Fijos registrados (vinculados a recurrentes): {money(s.fixed, currency)} · Otros / variables: {money(s.variable, currency)}</p></div> : <Empty>No hay gastos confirmados en este período.</Empty>}</Surface><Surface title="Próximos pagos"><Upcoming events={s.upcoming.slice(0, 5)} currency={currency} pay={(e: any) => recurringPayment(e, snapshot, edit)} /><Link className="mt-4 inline-block text-sm text-primary" to="/finanzas/calendario">Ver próximos meses y cuotas</Link></Surface></div>
                <Surface title="Evolución mensual · moneda original"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="py-3 pr-4">Mes</th><th className="pr-4">Ingresos</th><th className="pr-4">Gastos netos</th><th>Diferencia</th></tr></thead><tbody>{snapshot.history.map((h: any) => <tr key={h.month} className="border-b border-border/50"><td className="py-3 pr-4">{h.month}</td><td className="whitespace-nowrap pr-4">{money(h.income, currency)}</td><td className="whitespace-nowrap pr-4">{money(h.expenses, currency)}</td><td className="whitespace-nowrap">{money(h.difference, currency)}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-muted-foreground">La variación del gasto no mide inflación personal: puede cambiar por cantidad, categorías o datos faltantes.</p></Surface>
                {snapshot.conversion && <Surface title="Conversión opcional · ARS + USD"><p className="text-sm">Ingresos: {money(snapshot.conversion.income)} · Gastos: {money(snapshot.conversion.expenses)}</p><p className="mt-2 text-xs text-muted-foreground">1 USD = {money(snapshot.conversion.usdToArs)} · Fuente manual: {snapshot.conversion.source} · Fecha: {snapshot.conversion.date}. Un único criterio para el período, no cotización histórica por operación. Excluye EUR. Los importes originales no cambian.</p></Surface>}
                {snapshot.preferences.includePortfolio && <Surface title="Portafolio · vista voluntaria y privada">{snapshot.portfolio?.unavailable ? <p>No se pudo cargar tu portafolio.</p> : Array.isArray(snapshot.portfolio) && snapshot.portfolio.length ? snapshot.portfolio.map((p: any) => <p key={p.id} className="mb-2 text-sm">{p.name} · {p.currency} · {p.positions} posiciones registradas</p>) : <Empty>No hay portafolios registrados.</Empty>}<Link className="mt-3 inline-block text-sm text-primary" to="/portfolio">Ver inversiones</Link><p className="mt-2 text-xs text-muted-foreground">Resumen de posiciones; consultá valuaciones y cotizaciones en Portafolio. Tus movimientos financieros no se publican ni crean operaciones de inversión.</p></Surface>}
            </>}
            {tab === 'movimientos' && <Surface title="Movimientos del mes"><div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Buscar"><input className={fieldClass} value={search} placeholder="Descripción, comercio o notas" onChange={e => setSearch(e.target.value)} /></Field><Field label="Estado"><select className={fieldClass} value={status} onChange={e => setStatus(e.target.value)}><option value="all">Todos</option><option value="confirmed">Confirmados</option><option value="pending">Por revisar</option></select></Field><Field label="Tipo"><select className={fieldClass} value={type} onChange={e => setType(e.target.value)}><option value="all">Todos</option>{Object.entries(kinds).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></Field><Field label="Categoría"><select className={fieldClass} value={category} onChange={e => setCategory(e.target.value)}><option value="all">Todas</option>{[...new Set<string>([...snapshot.preferences.categories, ...snapshot.transactions.map((t: any) => t.category)])].map(c => <option key={c}>{c}</option>)}</select></Field></div>{transactions.length ? <div className="divide-y divide-border">{transactions.map((t: any) => <div key={t.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold">{t.description}</p><p className="mt-1 text-xs text-muted-foreground">{t.date.slice(0, 10)} · {kinds[t.type]} · {t.category} · {meta(t).origin === 'csv' ? 'CSV' : 'Manual'}</p><p className={`mt-1 text-xs ${t.status === 'pending' || meta(t).incomplete ? 'text-amber-600 dark:text-amber-400' : 'text-muted-foreground'}`}>{t.status === 'pending' ? 'Pendiente de revisión: editar para confirmar' : 'Confirmado'}{meta(t).incomplete ? ' · Datos incompletos' : ''}{meta(t).installments ? ` · ${meta(t).installments} cuotas` : ''}</p></div><p className="text-sm font-semibold tabular-nums">{money(t.amount, t.currency)}</p>{actions('transactions', t)}</div>)}</div> : <Empty>No hay movimientos para estos filtros. Podés agregar uno o importar un CSV.</Empty>}</Surface>}
            {resources[tab] && <Surface title={tabs.find(([p]) => p === tab)?.[1]}><Button className="mb-5" size="sm" onClick={() => edit(resources[tab])}><Plus size={14} className="mr-1" />Agregar</Button><div className="grid gap-4 md:grid-cols-2">{(tab === 'presupuestos' ? s.budgets : tab === 'cuentas' ? s.accounts : snapshot[resources[tab]].filter((r: any) => tab === 'tarjetas' || r.currency === currency)).map((r: any) => <div key={r.id} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-semibold">{r.name || r.category}</h3>{actions(resources[tab], r)}</div>
                {tab === 'cuentas' && <><p className="mt-3 text-xl font-semibold">{money(r.calculatedBalance, r.currency)}</p><p className="mt-1 text-xs text-muted-foreground">Saldo calculado actual, no bancario · Inicial: {money(r.openingBalance, r.currency)} · {r.institution || r.kind}</p></>}
                {tab === 'tarjetas' && <CardSummary card={r} summary={snapshot.cardSummary.find((s: any) => s.cardId === r.id)} currency={currency} edit={edit} />}
                {tab === 'presupuestos' && <><p className="mt-3 text-sm">Usado: {money(r.spent, currency)} de {money(r.limit, currency)}</p><progress className="my-2 h-2 w-full accent-primary" max={Number(r.limit) || 1} value={Math.max(0, r.spent)} /><p className="text-xs text-muted-foreground">Restante: {money(r.remaining, currency)} · Aviso al {r.alertAt}%</p>{r.alert && <p className="mt-2 text-sm text-amber-600 dark:text-amber-400">Alcanzaste el umbral elegido.</p>}</>}
                {tab === 'objetivos' && <><p className="mt-3 text-sm">{money(r.saved, r.currency)} de {money(r.target, r.currency)}</p><progress className="my-2 h-2 w-full accent-primary" max={Number(r.target) || 1} value={Number(r.saved)} /><p className="text-xs text-muted-foreground">{r.deadline ? `Objetivo: ${r.deadline.slice(0, 10)}` : 'Sin fecha límite'} · Registro manual, separado de inversiones.</p><Button variant="outline" size="sm" className="mt-3" onClick={() => { setConfirmation({ contribute: true, row: r }); setConfirmationText(''); }}>Registrar aporte</Button></>}
            </div>)}</div>{!(tab === 'presupuestos' ? s.budgets : snapshot[resources[tab]]).length && <Empty>Todavía no hay registros. Agregá el primero.</Empty>}</Surface>}
            {tab === 'calendario' && <><Surface title="Próximos meses · cuotas y vencimientos"><p className="mb-4 text-sm text-muted-foreground">Compromisos pendientes hasta 12 meses desde el período elegido. Las cuotas no vuelven a contar como gasto. Las fechas de cierre son orientativas; revisalas contra tu resumen.</p><Upcoming events={s.upcoming} currency={currency} pay={(e: any) => recurringPayment(e, snapshot, edit)} grouped /></Surface><Surface title="Servicios y gastos recurrentes"><Button size="sm" className="mb-4" onClick={() => edit('recurring')}>Agregar recurrente</Button>{snapshot.recurring.filter((r: any) => r.currency === currency).map((r: any) => { const price = snapshot.recurringChanges.find((c: any) => c.id === r.id); return <div key={r.id} className="flex flex-wrap justify-between gap-3 border-t border-border py-4"><div><p className="text-sm font-semibold">{r.name} · {money(r.amount, r.currency)}</p><p className="text-xs text-muted-foreground">{r.active ? 'Activo' : 'Pausado'} · Desde {r.nextDate.slice(0, 10)} · {r.category}</p>{price?.previous != null && <p className="mt-1 text-xs text-muted-foreground">Últimos pagos: {money(price.previous, currency)} → {money(price.latest, currency)}. Variación del cargo registrado, no inflación.</p>}</div>{actions('recurring', r)}</div>})}<p className="mt-3 text-xs text-muted-foreground">Los importes futuros son estimados; un vencimiento se resuelve registrando su pago. Los avisos se activan en Ajustes.</p></Surface></>}
            {tab === 'importar' && <WorkspaceImport snapshot={snapshot} saved={reload} edit={edit} />}
            {tab === 'configuracion' && <WorkspaceSettings preferences={snapshot.preferences} saved={reload} erase={() => { setConfirmation({ erase: true }); setConfirmationText(''); }} />}
            {tab === 'inversiones' && <Surface title="Integración voluntaria"><p className="text-sm text-muted-foreground">Activá la vista privada de Portafolio en Ajustes. Los movimientos nunca se convierten automáticamente en inversiones.</p><Link className="mt-4 inline-block text-primary" to="/finanzas/configuracion">Ir a Ajustes</Link></Surface>}
        </>}
        {editor && snapshot && <WorkspaceEditor {...editor} snapshot={snapshot} month={month} currency={currency} close={() => setEditor(null)} saved={reload} />}
        {confirmation && <Dialog open onOpenChange={v => !v && !busy && setConfirmation(null)}><DialogContent><DialogTitle>{confirmation.contribute ? 'Registrar aporte manual' : confirmation.erase ? 'Eliminar Finanzas Personales' : 'Eliminar registro'}</DialogTitle><DialogDescription>{confirmation.contribute ? 'Este aporte actualiza la meta. No mueve dinero ni modifica cuentas o Portafolio.' : confirmation.erase ? 'Se eliminarán tus movimientos, cuentas, tarjetas, metas, presupuestos, reglas y avisos financieros. No se puede deshacer desde la aplicación.' : 'Este registro se eliminará de tus datos. Los informes se recalcularán. Esta acción no se puede deshacer.'}</DialogDescription>{(confirmation.erase || confirmation.contribute) && <Field label={confirmation.erase ? 'Escribí ELIMINAR FINANZAS' : `Importe ${confirmation.row.currency}`}><input className={fieldClass} type={confirmation.contribute ? 'number' : 'text'} min={confirmation.contribute ? '.01' : undefined} step={confirmation.contribute ? '.01' : undefined} value={confirmationText} onChange={e => setConfirmationText(e.target.value)} /></Field>}{message && <p role="status" className="text-sm">{message}</p>}<Button variant={confirmation.contribute ? 'default' : 'destructive'} disabled={busy || (confirmation.erase && confirmationText !== 'ELIMINAR FINANZAS') || (confirmation.contribute && Number(confirmationText) <= 0)} onClick={execute}>{busy ? 'Guardando…' : 'Confirmar'}</Button></DialogContent></Dialog>}
    </main>;
}

function CardSummary({ card, summary, currency, edit }: any) {
    return <><p className="mt-2 text-xs text-muted-foreground">{card.brand} {card.last4 ? `•••• ${card.last4}` : ''} · Cierre día {card.closingDay || 'sin definir'} · Vence día {card.dueDay || 'sin definir'}</p><div className="mt-3 space-y-2 text-sm"><p>Deuda calculable pendiente: {money(summary?.debt, currency)}</p><p>Próximo pago estimado: {summary?.nextDate ? `${money(summary.nextAmount, currency)} · ${summary.nextDate}` : 'Sin compromisos calculables'}</p><p>Compras del ciclo que cierra {summary?.closing || 'sin definir'}: {money(summary?.statementPurchases, currency)}</p></div><p className="mt-2 text-xs text-muted-foreground">{summary?.incomplete ? 'Información incompleta. ' : ''}Saldos informativos, no un resumen bancario. Cambiá entre ARS y USD para ver cada moneda. Los cierres se estiman por día calendario.</p><Button size="sm" variant="outline" className="mt-3" onClick={() => edit('transactions', { type: 'card_payment', cardId: card.id })}>Registrar pago parcial o total</Button></>;
}
function recurringPayment(event: any, snapshot: any, edit: any) {
    const recurring = snapshot.recurring.find((r: any) => r.id === event.recurringId);
    if (recurring) edit('transactions', { type: 'expense', description: recurring.name, amount: event.amount, currency: event.currency, category: recurring.category, accountId: recurring.accountId, details: { recurringId: recurring.id, occurrence: event.date } });
}
function Upcoming({ events, currency, pay, grouped = false }: any) {
    if (!events.length) return <Empty>No hay compromisos calculables para este período y moneda. Los datos incompletos no se proyectan.</Empty>;
    const groups: Record<string, any[]> = {};
    for (const e of events) { const key = grouped ? e.date.slice(0, 7) : 'Próximos'; (groups[key] ||= []).push(e); }
    return <div className="space-y-5">{Object.entries(groups).map(([month, rows]) => <div key={month}>{grouped && <h3 className="mb-2 flex flex-wrap justify-between gap-2 text-sm font-semibold"><span>{month}</span><span>{money(rows.reduce((sum, e) => sum + e.amount, 0), currency)}</span></h3>}<div className="divide-y divide-border">{rows.map((e: any) => <div key={e.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="min-w-0 flex-1"><p className="break-words text-sm">{e.title}</p><p className="mt-1 text-xs text-muted-foreground">{e.date}{e.overdue ? ' · Anterior al período / pendiente' : ''}{e.count ? ` · Cuota ${e.installment}/${e.count}` : ''}{e.estimated ? ' · Importe estimado' : ''}</p></div><span className="text-sm tabular-nums">{money(e.amount, currency)}</span>{e.recurringId && <Button size="sm" variant="outline" onClick={() => pay(e)}>Registrar pago</Button>}</div>)}</div></div>)}</div>;
}
